import { dbConnect } from "@/services/mongo";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "LearnScape - World's Best Learning Platform",
    description: "Generated by Shadipto Mojumder",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    await dbConnect();

    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
            <Toaster richColors/>
        </html>
    );
}
